_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  antibot: 0
  auto_entitylabel: 0
  automated_cron: 0
  block: 0
  block_content: 0
  bpmn_io: 0
  breakpoint: 0
  bulk_update_fields: 0
  ckeditor5: 0
  config: 0
  config_pages: 0
  contextual: 0
  csv_serialization: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  eca: 0
  eca_content: 0
  eca_modeller_bpmn: 0
  eca_ui: 0
  editor: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  link: 0
  mailsystem: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quicklink: 0
  r4032login: 0
  registration_role: 0
  rest: 0
  sendgrid_integration: 0
  sendgrid_integration_reports: 0
  serialization: 0
  stage_file_proxy: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  user_registrationpassword: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  youtube: 0
  pathauto: 1
  views: 10
  login_redirect_per_role: 1000
  standard: 1000
theme:
  claro: 0
  pubsub: 0
  gin: 0
profile: standard
