attributes:
  container_class:
    label: ''
    description: ''
    container: true
  container_data-date:
    label: 'Date for session schedule tabs'
    description: 'Machine readable date (eg <code>2022-02-19</code>). This is used by the session schedule''s tab navigation.'
    container: true
