_core:
  default_config_hash: oLgmGR2Jq98YjM80b7XIU7o_u9PTxwj0P23G60FQiaE
ignore_admin_paths: true
ignore_ajax_links: true
ignore_hashes: true
ignore_file_ext: true
url_patterns_to_ignore: /contact
ignore_selectors: ''
selector: ''
allowed_domains: ''
prefetch_only_paths: ''
no_load_when_authenticated: true
no_load_when_session: true
no_load_content_types: {  }
total_request_limit: 0
concurrency_throttle_limit: 0
viewport_delay: 0
idle_wait_timeout: 2000
load_polyfill: false
enable_debug_mode: false
