_core:
  default_config_hash: sd6r3H04eOul_dps8oyinjacaZmLgG7BrRZ3bmYiyZU
langcode: en
register_confirmation_with_pass:
  subject: 'Action required: Activate account for [user:display-name] at [site:name]'
  body: "[user:display-name],\r\n\r\nThank you for registering at [site:name]. You must activate your account by clicking the URL below:\r\n\r\n[user:registrationpassword-url]?destination=node/280\r\n\r\nThis link can only be used once. You will be able to log in at [site:login-url] in the future using:\r\n\r\nusername: [user:name]\r\npassword: your password\r\n\r\n--  [site:name] team"
