_core:
  default_config_hash: 2fwxXOq3dbjiboKslfHTJXYWAk4u1zadK65SRiDrxug
registration: with-pass
registration_ftll_expire: false
registration_ftll_timeout: 86400
notify:
  register_confirmation_with_pass: true
