status_activated:
  subject: 'Account details for [user:display-name] at [site:name] (approved)'
  body: "[user:display-name],\n\nYour account at [site:name] has been activated.\n\nYou may now log in by clicking this link or copying and pasting it into your browser:\n\n[user:one-time-login-url]\n\nThis link can only be used once to log in and will lead you to a page where you can set your password.\n\nAfter setting your password, you will be able to log in at [site:login-url] in the future using:\n\nusername: [user:account-name]\npassword: Your password\n\n--  [site:name] team"
langcode: en
_core:
  default_config_hash: '-NFASedvrCq04dzkSi6iBCauY3BLjVOxfRNcOKN09kA'
